import { useNavigate } from "react-router-dom";
import Button from "../components/Button";

export default function AccountServices({ user }) {
  const navigate = useNavigate();

  const handleGetStarted = () => {
    navigate("/tokenize-company");
  };

  return (
    <div className="min-h-screen bg-gray-100 flex flex-col items-center py-8 px-4">
      <header className="w-full max-w-3xl mb-8">
        <div className="bg-white rounded-lg shadow-md p-6 flex flex-col items-center">
          <div className="w-24 h-24 bg-blue-500 rounded-full flex items-center justify-center mb-4">
            <span className="text-white text-3xl font-bold">Logo</span>
          </div>
          <h1 className="text-2xl font-bold mb-2">Account Address</h1>
          <p className="text-lg mb-1">{user.finternentId}</p>
          <p className="text-sm text-gray-500">Generated by Finternet</p>
        </div>
      </header>
      <main className="w-full max-w-3xl">
        <section className="bg-white rounded-lg shadow-md p-6">
          <h2 className="text-xl font-semibold mb-4">Services Provided</h2>
          <div className="space-y-4">
            <div className="border border-gray-200 rounded-md p-4">
              <h3 className="text-lg font-medium mb-2">Link your invoice</h3>
              <p className="text-gray-600 mb-4">
                Connect your invoices to streamline your financial processes.
              </p>
              <Button onClick={handleGetStarted}>Get Started</Button>
            </div>
            <div className="border border-gray-200 rounded-md p-4">
              <h3 className="text-lg font-medium mb-2">Another Service</h3>
              <p className="text-gray-600 mb-4">
                Description of another service provided by Finternet.
              </p>
              <Button>Get Started</Button>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
